### ISSUE TITLE
Upgrade from Wildfly8 to Wildfly 10 fails, no redirection for SAML protocol

### ISSUE THREAD

**Issue by sutrap** [soulwing/cas-extension#12]
Hi,

I'm having problems with upgrading my wildfly 8 to 10 and CAS 4 to CAS 5.
I'm using SAML with attributes on cas which
ItCas logon itself works well. 
cas-extension seemst to work also... 
But after a successfull logon there is no redirect to the service url...
URL is like https://..../cas/login?TARGET=.......
I'm using the actual CAS version 5.1.3.
CAS is configured for SAML-1.1 protocol.

Any clue whats wrong?

**Comment by ceharris** [comment]
I've got production deployments using the extension with SAML-1.1 under Wildfly 10 without issue. I can't speak to which versions of the CAS server might be in use. The redirect to the SAML target URL is something that should be done by the CAS server.

Check that the URL that you see for TARGET=... when the browser is redirected to your login server is correct; if not check the `serviceUrl` property of the extension.

**Comment by sutrap** [comment]
Well... I figured out that my cas server was missing SAML extension. 
There was no redirection done..
So I added saml support to my cas server overlay and now I'm stuck deploying cas.war on wildfly 10 server... 

Log says:
WARN  [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] (ServerService Thread Pool -- 112) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.OpenSAMLConfig' defined in class path resource [org/apereo/cas/config/CoreSamlConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apereo.cas.support.saml.OpenSamlConfigBean]: Factory method 'openSamlConfigBean' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.ParserPool' defined in class path resource [org/apereo/cas/config/CoreSamlConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [net.shibboleth.utilities.java.support.xml.BasicParserPool]: Factory method 'parserPool' threw exception; nested exception is java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.org.apache.xerces.internal.util.SecurityManager from [Module "deployment.cas.war:main" from Service Module Loader]
22:16:43,279 ERROR [org.springframework.boot.SpringApplication] (ServerService Thread Pool -- 112) Application startup failed: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.OpenSAMLConfig' defined in class path resource [org/apereo/cas/config/CoreSamlConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apereo.cas.support.saml.OpenSamlConfigBean]: Factory method 'openSamlConfigBean' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.ParserPool' defined in class path resource [org/apereo/cas/config/CoreSamlConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [net.shibboleth.utilities.java.support.xml.BasicParserPool]: Factory method 'parserPool' threw exception; nested exception is java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.org.apache.xerces.internal.util.SecurityManager from [Module "deployment.cas.war:main" from Service Module Loader]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)


Right now I'm unable to get it running as it seems cas saml is missing sonething... Or I've not configured it rightly... 
any clue?
