### ISSUE TITLE
Wildfly 14 support

### ISSUE THREAD

**Issue by sutrap** [soulwing/cas-extension#14]
Is it possible to adapt the module for wildfly up to 14?

**Comment by ceharris** [comment]
Yes. I've actually got a work project that uses this extension that needs to get updated from Wildfly 10 to Wildfly 12-14. We're scheduled do to that work between mid-November and mid-December, which means we'll be updating this extension during that same timeframe.

**Comment by sutrap** [comment]
Maybe you can check my patch. It compiles now with wildfly14 profile...
I will make more checks on weekend.
[wildfly14.zip](https://github.com/soulwing/cas-extension/files/2564071/wildfly14.zip)

**Comment by ceharris** [comment]
Have you been successfully running the extension with this patch applied?

**Comment by sutrap** [comment]
Yes. my config works so far. Do you have problems?

I didn't check any side effects and tried just to get it working, what it
did :D



Am Di., 11. Dez. 2018 um 19:19 Uhr schrieb Carl Harris <
notifications@github.com>:

**Comment by ceharris** [comment]
No problems, just wanted to confirm that someone else was testing it before I merged the patch into the code base.

**Comment by ceharris** [comment]
I created PR #15 from your patch and merged it. I need to do some more testing myself before I create a new versioned release.

**Comment by sutrap** [comment]
You might consider that it breaks other versions!

As the API changed I dont think it is possible to have a common codebase
for wildfly 10 and wildfly 14...


Am Di., 11. Dez. 2018 um 19:55 Uhr schrieb Carl Harris <
notifications@github.com>:

**Comment by ceharris** [comment]
Understood.

**Comment by singhindresh** [comment]
Hi Carl,  Can you please provide build instruction for wildfly 14. I'm trying to build the master with "mvn clean install" but I'm getting error. Thanks for your help.

Regards,
 Indresh

**Comment by ceharris** [comment]
It is necessary to enable two maven build profiles, similar to what was needed for Wildfly 10. I've updated the README, accordingly

**Comment by singhindresh** [comment]
Thanks Carl! Web authentication is working but EJB authentication is failing. I assume setup should work as in legacy security subsystem (PicketBox).

Exception stack trace:
org.jboss.as.ejb3.security.AuthorizationInterceptor.processInvocation(AuthorizationInterceptor.java:134)
org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)

**Comment by singhindresh** [comment]
Carl, I was able to resolve the issue. My EJB authentication error was due to default-missing-method-permissions-deny-access.

**Comment by ceharris** [comment]
Awesome. Glad to know that still works!
